source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

gem 'rails', '~> 7.1'
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.4'
gem 'graphql', '~> 2.3'
gem 'rack-cors'
gem 'bootsnap', require: false

group :development do
  gem 'graphiql-rails'
end

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end
